language: node_js

node_js:
  - 'node'
  - '10'

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: always

install: yarn

script:
  - yarn lint

branches:
  only: master
