language: node_js

node_js:
  - 'node' # stable version

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: always

install: yarn

script:
  - yarn build