baseurl = "https://endormi.io/"

title = "Endormi"

theme = "hugo-coder"

languagecode = "en"

defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"

pygmentscodefences = true

pygmentscodefencesguesssyntax = true

[params]
    author = "Erno Salo"

    info = "Software Developer at Foredata Oy"

    description = "Endormi's personal website"

    keywords = "developer,personal,website,portfolio"

    avatarurl = "images/avi.png"

    favicon_32 = "images/avi.png"

    favicon_16 = "images/avi.png"

    hidecredits = true

    rtl = false

    custom_css = ["/css/custom.css"]

[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/endormi/"

[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://linkedin.com/in/ernosalo/"

[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/_endormi/"

[[params.social]]
    name = "Dev.to"
    icon = "fab fa-dev fa-2x"
    weight = 4
    url = "https://dev.to/endormi/"

[[params.social]]
    name = "NPM"
    icon = "fab fa-npm fa-2x"
    weight = 5
    url = "https://www.npmjs.com/~endormi"


[languages]
    [languages.en]
        languagename = "EN"

            [languages.en.menu]

                [[languages.en.menu.main]]
                    name = "Home"
                    weight = 1
                    url = "/"

                [[languages.en.menu.main]]
                    name = "About"
                    weight = 2
                    url = "/about/"

                [[languages.en.menu.main]]
                    name = "Open Source"
                    weight = 3
                    url = "/open-source/"

                [[languages.en.menu.main]]
                    name = "Posts"
                    weight = 4
                    url = "https://dev.to/endormi"

                [[languages.en.menu.main]]
                    name = "Uses"
                    weight = 5
                    url = "/uses/"

                [[languages.en.menu.main]]
                    name = "Contact"
                    weight = 6
                    url  = "mailto:contactendormi@gmail.com"

    [languages.fr]
        languagename = "FR"
        title = "Erno Salo"

        [languages.fr.params]
            author = "Erno Salo"
            info = "Développeur logiciel à Foredata Oy"
            description = "Le site personnel de Endormi"
            keywords = "développeur,personnel,site,portefeuille"

                [languages.fr.menu]

                    [[languages.fr.menu.main]]
                        name = "Accueil"
                        weight = 1
                        url = "/"

                    [[languages.fr.menu.main]]
                        name = "À propos"
                        weight = 2
                        url = "/about/"

                    [[languages.fr.menu.main]]
                        name = "Open Source"
                        weight = 3
                        url = "/open-source/"

                    [[languages.fr.menu.main]]
                        name = "Des postes"
                        weight = 4
                        url = "https://dev.to/endormi"

                    [[languages.fr.menu.main]]
                        name = "Les usages"
                        weight = 5
                        url = "/uses/"

                    [[languages.fr.menu.main]]
                        name = "Contact"
                        weight = 6
                        url  = "mailto:contactendormi@gmail.com"
